import { NextRequest, NextResponse } from 'next/server';
import { getAuthenticatedUser, getServerClient } from '@/lib/insforge/server';
import { getActiveWorkspaceId } from '@/lib/workspace';
import { enrichCapture } from '@/lib/event-capture/enrich';

interface RouteParams {
  params: { id: string };
}

/**
 * POST /api/event-capture/[id]/regenerate-questions
 * Reloads the question set for ONE event without re-importing the whole calendar.
 * Re-runs Stage-2 enrichment (fresh research + new LLM questions) and, only once
 * that succeeds, clears the stored answers (the caller confirms this in the UI)
 * so a mid-flight failure never destroys answers the user already gave without
 * actually producing new questions. Because questions are generated by the LLM
 * each call, this produces a genuinely different set - not the previously cached one.
 */
export async function POST(
  _request: NextRequest,
  { params }: RouteParams,
): Promise<NextResponse> {
  const user = await getAuthenticatedUser();
  if (!user) return NextResponse.json({ error: 'Unauthorized' }, { status: 401 });

  const workspaceId = await getActiveWorkspaceId(user.id);
  if (!workspaceId) return NextResponse.json({ error: 'No active workspace' }, { status: 400 });

  const client = getServerClient();

  // Ownership check before doing any work.
  const { data: capture } = await client.database
    .from('event_captures')
    .select('id, workspace_id')
    .eq('id', params.id)
    .eq('workspace_id', workspaceId)
    .single();

  if (!capture) return NextResponse.json({ error: 'Capture not found' }, { status: 404 });

  try {
    const outcome = await enrichCapture(client, params.id, new Date(), { ignoreRecency: true });
    if (outcome !== 'questions_ready') {
      return NextResponse.json({ error: `Could not reload questions (${outcome})` }, { status: 502 });
    }

    // Only clear stored answers once new questions actually landed, so a failed
    // or blocked reload never wipes answers the user already gave.
    await client.database
      .from('event_captures')
      .update({ answers: {}, updated_at: new Date().toISOString() })
      .eq('id', params.id)
      .eq('workspace_id', workspaceId);

    return NextResponse.json({ ok: true, status: 'questions_ready' });
  } catch (err) {
    console.error('[event-capture/regenerate-questions] error', err);
    return NextResponse.json({ error: 'Failed to reload questions' }, { status: 500 });
  }
}
