import type { SocialPlatform } from '@/lib/social/types';

/** How a series lays out on the calendar. Stored as jsonb on series.cadence. */
export interface SeriesCadence {
  /** Lowercase weekday names the series posts on, e.g. ['tue','thu']. */
  days: string[];
  /** Local wall-clock time, 'HH:MM' 24h. */
  time: string;
  /** IANA tz label for display; scheduling treats time as the server clock (see schedule.ts). */
  tz?: string;
  /** First eligible date, 'YYYY-MM-DD'. */
  start_date: string;
  /** Post on every Nth eligible week (1 = every week). */
  interval_weeks?: number;
}

export type SeriesStatus = 'draft' | 'active' | 'paused' | 'completed';
export type SourceKind = 'file' | 'text' | 'url' | 'story_bank' | 'post';
export type SourceStatus = 'pending' | 'ready' | 'failed';

export interface SeriesRow {
  id: string;
  user_id: string;
  workspace_id: string | null;
  name: string;
  description: string | null;
  pillar: string;
  total_parts: number;
  platform: SocialPlatform | null;
  cadence: SeriesCadence | null;
  status: SeriesStatus;
  auto_publish: boolean;
  source_summary: string | null;
  created_at: string;
}

export interface SeriesSource {
  id: string;
  series_id: string;
  kind: SourceKind;
  title: string | null;
  source_ref: string | null;
  char_count: number;
  status: SourceStatus;
  error: string | null;
  created_at: string;
}

/** One planned part of a series, generated by the arc step. */
export interface SeriesArcPart {
  position: number;
  title: string;
  hook: string;
  core_point: string;
  bridge: string;
}
